CREATE TABLE departments (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', leader_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE users (id TEXT PRIMARY KEY, username TEXT UNIQUE, password_hash TEXT, display_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, role TEXT NOT NULL CHECK(role IN ('MEMBER','DEPARTMENT_LEAD','ADMIN')), department_id TEXT REFERENCES departments(id), bio TEXT NOT NULL DEFAULT '', is_active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE chronicles (id TEXT PRIMARY KEY, title TEXT NOT NULL, content TEXT NOT NULL, occurred_at TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE activities (id TEXT PRIMARY KEY, department_id TEXT REFERENCES departments(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('PREPARING','REGISTRATION','IN_PROGRESS','ENDED','ARCHIVED')), capacity INTEGER NOT NULL CHECK(capacity > 0), check_in_code TEXT, result_summary TEXT, starts_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE activity_registrations (id TEXT PRIMARY KEY, activity_id TEXT NOT NULL REFERENCES activities(id), user_id TEXT NOT NULL REFERENCES users(id), registered_at TEXT NOT NULL, checked_in_at TEXT, UNIQUE(activity_id,user_id));
CREATE TABLE activity_results (id TEXT PRIMARY KEY, activity_id TEXT NOT NULL REFERENCES activities(id), summary TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE applications (id TEXT PRIMARY KEY, status_token_hash TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, email TEXT NOT NULL, department_id TEXT NOT NULL REFERENCES departments(id), reason TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('PENDING','APPROVED','REJECTED')), user_id TEXT REFERENCES users(id), activation_code_encrypted TEXT, rejection_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE activation_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE works (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), department_id TEXT NOT NULL REFERENCES departments(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT NOT NULL CHECK(status IN ('PENDING','PUBLISHED','REJECTED')), review_note TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE files (id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), department_id TEXT REFERENCES departments(id), name TEXT NOT NULL, storage_key TEXT NOT NULL UNIQUE, mime_type TEXT NOT NULL, size INTEGER NOT NULL, visibility TEXT NOT NULL CHECK(visibility IN ('PUBLIC','MEMBERS','DEPARTMENT','ADMINS')), deleted_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE department_tasks (id TEXT PRIMARY KEY, department_id TEXT NOT NULL REFERENCES departments(id), assignee_id TEXT NOT NULL REFERENCES users(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', due_at TEXT, completed_at TEXT, confirmed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE site_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, actor_id TEXT REFERENCES users(id), target_user_id TEXT REFERENCES users(id), action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, details TEXT, created_at TEXT NOT NULL, UNIQUE(action,entity_type,entity_id,target_user_id));

