import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity as ActivityIcon, ArchiveRestore, Ban, Check, CircleGauge, ClipboardCheck, FileArchive, History, ListChecks, RotateCcw, Search, Settings, ShieldCheck, Trash2, UserCog, Users, X } from 'lucide-react';
import { api, json, type PageData } from './api';
import { useAuth } from './auth';
import { EmptyPanel, ErrorPanel, formatDate, LoadingPanel, PageHero, StatusBadge } from './components';
import type { Activity, Department } from './pages-public';

interface Dashboard { members:number; pendingApplications:number; activeActivities:number; publishedWorks:number }
interface Analytics { departmentActivity:Array<{departmentId:string;departmentName:string;score:number}>; memberGrowth:Array<{month:string;count:number}> }
interface Member { id:string; display_name:string; email:string; role:string; department_id:string|null; is_active:number; created_at:string }
interface Application { id:string; display_name:string; email:string; college:string; department_id:string; reason:string; status:string; rejection_reason?:string; created_at:string }
interface Work { id:string; title:string; description:string; status:string; department_id:string; display_name?:string; created_at:string }
interface GuildFile { id:string; name:string; mime_type:string; size:number; visibility:string; category:string; department_id:string|null; deleted_at:string|null }
interface Task { id:string; title:string; description:string; department_id:string; assignee_id:string; completed_at?:string; confirmed_at?:string; due_at?:string }
interface Audit { id:string; action:string; entity_type:string; entity_id:string; actor_id?:string; created_at:string }
interface Chronicle { id:string; title:string; content:string; occurred_at:string }

function useInvalidate(...keys:string[]){const client=useQueryClient();return ()=>keys.forEach(key=>client.invalidateQueries({queryKey:[key]}));}

export function AdminDashboardPage(){
  const dashboard=useQuery({queryKey:['admin-dashboard'],queryFn:()=>api<Dashboard>('/api/admin/dashboard')});
  const analytics=useQuery({queryKey:['admin-analytics'],queryFn:()=>api<Analytics>('/api/admin/analytics')});
  const stats=[['正式成员',dashboard.data?.members??0,Users],['待审申请',dashboard.data?.pendingApplications??0,ListChecks],['活跃活动',dashboard.data?.activeActivities??0,ActivityIcon],['已发作品',dashboard.data?.publishedWorks??0,ShieldCheck]] as const;
  return <main><PageHero eyebrow="COMMAND TABLE" title="公会数据总览" description="所有数值由成员、活动、作品与任务记录实时聚合。"/><section className="shell dashboard-cards">{stats.map(([label,value,Icon])=><article key={label}><Icon/><span>{label}</span><strong>{value}</strong></article>)}</section><section className="shell chart-grid"><article className="chart-panel"><h2>部门贡献排行</h2>{analytics.isLoading?<LoadingPanel/>:<ResponsiveContainer width="100%" height={300}><BarChart data={analytics.data?.departmentActivity??[]}><CartesianGrid strokeDasharray="3 3" stroke="#6c523b44"/><XAxis dataKey="departmentName"/><YAxis/><Tooltip/><Bar dataKey="score" fill="#c89b3c" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer>}</article><article className="parchment-panel"><h2>管理提醒</h2><div className="quest-row"><ListChecks/><span>待审核招新</span><strong>{dashboard.data?.pendingApplications??0}</strong></div><div className="quest-row"><ActivityIcon/><span>正在运行活动</span><strong>{dashboard.data?.activeActivities??0}</strong></div><p className="panel-note">处理操作会写入审计日志，成员与文件删除均可恢复。</p></article></section></main>;
}

export function MembersAdminPage(){
  const {user}=useAuth(); const [q,setQ]=useState(''); const [editing,setEditing]=useState<Member|null>(null); const refresh=useInvalidate('admin-members','admin-dashboard'); const query=useQuery({queryKey:['admin-members'],queryFn:()=>api<PageData<Member>>('/api/admin/members?page=1&pageSize=100')});
  const action=useMutation({mutationFn:({id,verb}:{id:string;verb:string})=>api(`/api/admin/members/${id}/${verb}`,json('POST')),onSuccess:refresh});
  const update=useMutation({mutationFn:(member:Member)=>api(`/api/admin/members/${member.id}`,json('PATCH',{displayName:member.display_name,...(user?.role==='ADMIN'&&member.role!=='DEPARTMENT_LEAD'?{role:member.role,departmentId:member.department_id}:{})})),onSuccess:()=>{setEditing(null);refresh();}});
  const items=query.data?.items.filter(m=>`${m.display_name}${m.email}`.toLowerCase().includes(q.toLowerCase()))??[];
  return <AdminListPage title="成员管理" eyebrow="MEMBER ROSTER" description="查询、编辑、停用与恢复成员档案；负责人调整在部门管理中完成。" search={q} onSearch={setQ}>{query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:<><div className="data-table"><div className="table-head"><span>成员</span><span>身份</span><span>部门</span><span>状态</span><span>操作</span></div>{items.map(m=><div className="table-row" key={m.id}><span><strong>{m.display_name}</strong><small>{m.email}</small></span><span>{m.role}</span><span>{m.department_id??'跨部门'}</span><span>{m.is_active?<StatusBadge status="APPROVED"/>:<StatusBadge status="REJECTED"/>}</span><span className="row-actions"><button onClick={()=>setEditing({...m})}><UserCog/>编辑</button>{m.id!==user?.id&&(m.is_active?<button onClick={()=>action.mutate({id:m.id,verb:'deactivate'})}><Ban/>停用</button>:<button onClick={()=>action.mutate({id:m.id,verb:'restore'})}><RotateCcw/>恢复</button>)}</span></div>)}</div>{editing&&<form className="inline-create" onSubmit={e=>{e.preventDefault();update.mutate(editing);}}><h2>编辑成员档案</h2><label>成员称呼<input minLength={2} required value={editing.display_name} onChange={e=>setEditing({...editing,display_name:e.target.value})}/></label>{user?.role==='ADMIN'&&editing.role!=='DEPARTMENT_LEAD'&&<><label>系统角色<select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value})}><option value="MEMBER">正式成员</option><option value="ADMIN">管理员</option></select></label><label>所属部门<select value={editing.department_id??''} onChange={e=>setEditing({...editing,department_id:e.target.value||null})}><option value="">跨部门</option><option value="dept-cos">COS部</option><option value="dept-tech">技术部</option><option value="dept-music">轻音部</option><option value="dept-original">原创部</option><option value="dept-dance">舞装部</option><option value="dept-publicity">外宣部</option></select></label></>}{editing.role==='DEPARTMENT_LEAD'&&<p className="panel-note">负责人角色和部门请在“部门管理”中调整。</p>}{update.error&&<p className="form-error">{update.error.message}</p>}<div className="form-actions"><button type="button" onClick={()=>setEditing(null)}>取消</button><button className="guild-button primary">保存档案</button></div></form>}</>}</AdminListPage>;
}

export function DepartmentsAdminPage(){
  const query=useQuery({queryKey:['departments'],queryFn:()=>api<{items:Department[]}>('/api/public/departments')}); const members=useQuery({queryKey:['admin-members','leaders'],queryFn:()=>api<PageData<Member>>('/api/admin/members?page=1&pageSize=100')}); const refresh=useInvalidate('departments','admin-members'); const [editing,setEditing]=useState<Department|null>(null); const update=useMutation({mutationFn:(d:Department)=>api(`/api/admin/departments/${d.id}`,json('PATCH',{title:d.title,description:d.description})),onSuccess:()=>{setEditing(null);refresh();}}); const assign=useMutation({mutationFn:({departmentId,userId}:{departmentId:string;userId:string})=>api(`/api/admin/departments/${departmentId}/leader`,json('POST',{userId})),onSuccess:refresh});
  return <main><PageHero eyebrow="CLASS ADMINISTRATION" title="部门管理" description="维护六个部门的职业称号、职责说明与负责人。"/><section className="shell">{query.isLoading?<LoadingPanel/>:<div className="manage-list">{query.data?.items.map(d=><article key={d.id}><div><small>{d.title}</small><h2>{d.name}</h2><p>{d.description}</p><label>部门负责人<select aria-label={`${d.name}负责人`} value={d.leader_id??''} onChange={e=>assign.mutate({departmentId:d.id,userId:e.target.value})}><option value="" disabled>选择负责人</option>{members.data?.items.filter(member=>member.department_id===d.id&&member.is_active).map(member=><option value={member.id} key={member.id}>{member.display_name}</option>)}</select></label></div><button onClick={()=>setEditing(d)}><UserCog/>编辑部门</button></article>)}</div>}{editing&&<form className="inline-create" onSubmit={e=>{e.preventDefault();update.mutate(editing);}}><h2>编辑 {editing.name}</h2><label>职业称号<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>部门说明<textarea value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label>{update.error&&<p className="form-error">{update.error.message}</p>}<div className="form-actions"><button type="button" onClick={()=>setEditing(null)}>取消</button><button className="guild-button primary">保存修改</button></div></form>}</section></main>;
}

export function ActivitiesAdminPage(){
  const refresh=useInvalidate('admin-activities','admin-dashboard','activities'); const [open,setOpen]=useState(false); const [generatedCodes,setGeneratedCodes]=useState<Record<string,string>>({}); const [resultFiles,setResultFiles]=useState<Record<string,File|null>>({}); const [resultSummaries,setResultSummaries]=useState<Record<string,string>>({}); const [uploadedResults,setUploadedResults]=useState<Record<string,string>>({}); const [form,setForm]=useState({departmentId:'dept-cos',title:'',description:'',location:'星门大厅',capacity:30,startsAt:'2026-08-20T10:00:00.000Z'});
  const query=useQuery({queryKey:['admin-activities'],queryFn:()=>api<PageData<Activity>>('/api/admin/activities?page=1&pageSize=100')});
  const create=useMutation({mutationFn:()=>api('/api/admin/activities',json('POST',form)),onSuccess:()=>{setOpen(false);refresh();}});
  const transition=useMutation({mutationFn:async({id,status,resultSummary}:{id:string;status:string;resultSummary?:string})=>{
    if(resultSummary) await api(`/api/admin/activities/${id}`,json('PUT',{resultSummary}));
    return api<{status:string;checkInCode?:string}>(`/api/admin/activities/${id}/state`,json('POST',{status}));
  },onSuccess:(data,variables)=>{if(data.checkInCode)setGeneratedCodes(current=>({...current,[variables.id]:data.checkInCode!}));refresh();}});
  const uploadResult=useMutation({mutationFn:async({id,file,summary}:{id:string;file:File;summary:string})=>{const body=new FormData();body.append('summary',summary||file.name);body.append('file',file);return api(`/api/admin/activities/${id}/results/upload`,{method:'POST',body});},onSuccess:(_data,variables)=>{setUploadedResults(current=>({...current,[variables.id]:variables.file.name}));refresh();}});
  const next:Record<string,string>={PREPARING:'REGISTRATION',REGISTRATION:'IN_PROGRESS',IN_PROGRESS:'ENDED',ENDED:'ARCHIVED'};
  return <main><PageHero eyebrow="QUEST OPERATIONS" title="活动管理" description="按筹备、报名、进行、结束、成果、归档推进完整生命周期。"><button className="guild-button primary" onClick={()=>setOpen(!open)}>{open?'取消创建':'创建活动'}</button></PageHero><section className="shell">{open&&<form className="inline-create" onSubmit={e=>{e.preventDefault();create.mutate();}}><label>活动名称<input required minLength={2} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>活动说明<textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>活动地点<input required minLength={2} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>开始时间<input type="datetime-local" required value={form.startsAt.slice(0,16)} onChange={e=>setForm({...form,startsAt:new Date(e.target.value).toISOString()})}/></label><label>人数上限<input type="number" min={1} value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})}/></label>{create.error&&<p className="form-error">{create.error.message}</p>}<button className="guild-button primary">保存筹备活动</button></form>}{query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:<div className="manage-list">{query.data?.items.map(a=><article key={a.id}><div><StatusBadge status={a.status}/><h2>{a.title}</h2><p>{a.description} · {a.location} · {formatDate(a.starts_at)}</p>{a.result_summary&&<small>成果：{a.result_summary}</small>}{generatedCodes[a.id]&&<strong className="check-in-code">签到码：{generatedCodes[a.id]}</strong>}{uploadedResults[a.id]&&<strong className="form-success">成果文件已上传：{uploadedResults[a.id]}</strong>}</div><div className="row-actions">{a.status==='ENDED'&&<div className="result-upload"><input aria-label={`${a.title}成果说明`} placeholder="成果说明" value={resultSummaries[a.id]??''} onChange={e=>setResultSummaries({...resultSummaries,[a.id]:e.target.value})}/><input aria-label={`${a.title}成果文件`} type="file" onChange={e=>setResultFiles({...resultFiles,[a.id]:e.target.files?.[0]??null})}/><button disabled={!resultFiles[a.id]||uploadResult.isPending} onClick={()=>{const file=resultFiles[a.id];if(file)uploadResult.mutate({id:a.id,file,summary:resultSummaries[a.id]??''});}}>上传成果文件</button></div>}{next[a.status]&&<button onClick={()=>{const resultSummary=a.status==='ENDED'?(resultSummaries[a.id]?.trim()||prompt('归档前填写成果摘要')||undefined):undefined;transition.mutate({id:a.id,status:next[a.status],resultSummary});}}>{next[a.status]==='REGISTRATION'?'开放报名':next[a.status]==='IN_PROGRESS'?'开始并生成签到码':next[a.status]==='ENDED'?'结束活动':'填写成果并归档'}</button>}</div></article>)}</div>}</section></main>;
}

export function RecruitmentAdminPage(){
  const refresh=useInvalidate('admin-applications','admin-dashboard'); const query=useQuery({queryKey:['admin-applications'],queryFn:()=>api<PageData<Application>>('/api/admin/applications?page=1&pageSize=100')}); const action=useMutation({mutationFn:({id,verb,body}:{id:string;verb:string;body?:unknown})=>api(`/api/admin/applications/${id}/${verb}`,json('POST',body)),onSuccess:data=>{const result=data as {activationCode?:string};if(result.activationCode)navigator.clipboard?.writeText(result.activationCode);refresh();}});
  return <main><PageHero eyebrow="RECRUITMENT DESK" title="招新管理" description="审核申请；通过后系统创建未激活成员并生成一次性激活码。"/><section className="shell">{query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:<div className="manage-list">{query.data?.items.map(a=><article key={a.id}><div><StatusBadge status={a.status}/><h2>{a.display_name}</h2><p>{a.college} · {a.email}</p><p>{a.reason}</p><small>{formatDate(a.created_at)}</small></div>{a.status==='PENDING'&&<div className="row-actions"><button onClick={()=>action.mutate({id:a.id,verb:'approve'})}><Check/>通过并复制激活码</button><button className="danger" onClick={()=>{const reason=prompt('填写拒绝原因');if(reason)action.mutate({id:a.id,verb:'reject',body:{reason}})}}><X/>拒绝</button></div>}{a.status==='APPROVED'&&<button onClick={()=>action.mutate({id:a.id,verb:'regenerate-activation'})}>重新生成激活码</button>}</article>)}</div>}</section></main>;
}

export function WorksAdminPage(){
  const {user}=useAuth(); const refresh=useInvalidate('admin-works','admin-dashboard','works'); const [status,setStatus]=useState('PENDING'); const query=useQuery({queryKey:['admin-works',status],queryFn:()=>api<PageData<Work>>(`/api/admin/works?page=1&pageSize=100&status=${status}`)}); const review=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api(`/api/admin/works/${id}/review`,json('POST',{status})),onSuccess:refresh});
  return <main><PageHero eyebrow="CURATION DESK" title="作品审核" description={`${user?.role==='ADMIN'?'全社':'本部门'}作品进入公开图鉴前需完成审核。`}/><section className="shell"><div className="filter-bar">{['PENDING','PUBLISHED','REJECTED'].map(s=><button className={status===s?'active':''} onClick={()=>setStatus(s)} key={s}>{s}</button>)}</div>{query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:!query.data?.items.length?<EmptyPanel label="当前队列为空"/>:<div className="manage-list">{query.data.items.map(w=><article key={w.id}><div><StatusBadge status={w.status}/><h2>{w.title}</h2><p>{w.description}</p></div>{w.status==='PENDING'&&<div className="row-actions"><button onClick={()=>review.mutate({id:w.id,status:'PUBLISHED'})}><Check/>发布</button><button className="danger" onClick={()=>review.mutate({id:w.id,status:'REJECTED'})}><X/>拒绝</button></div>}</article>)}</div>}</section></main>;
}

export function FilesAdminPage(){
  const {user}=useAuth();
  const refresh=useInvalidate('admin-files','member');
  const [open,setOpen]=useState(false);
  const [file,setFile]=useState<File|null>(null);
  const [visibility,setVisibility]=useState('MEMBERS');
  const [category,setCategory]=useState('OTHER');
  const [departmentId,setDepartmentId]=useState(user?.departmentId??'dept-cos');
  const query=useQuery({queryKey:['admin-files'],queryFn:()=>api<PageData<GuildFile>>('/api/admin/files?page=1&pageSize=100')});
  const action=useMutation({mutationFn:({id,verb}:{id:string;verb:string})=>api(`/api/admin/files/${id}/${verb}`,json('POST')),onSuccess:refresh});
  const rename=useMutation({mutationFn:({id,name}:{id:string;name:string})=>api(`/api/admin/files/${id}`,json('PATCH',{name})),onSuccess:refresh});
  const upload=useMutation({
    mutationFn:async()=>{
      if(!file)throw new Error('请选择文件');
      const body=new FormData();
      body.append('visibility',visibility);
      body.append('category',category);
      body.append('departmentId',departmentId);
      body.append('file',file);
      return api('/api/admin/files/upload',{method:'POST',body});
    },
    onSuccess:()=>{setOpen(false);setFile(null);refresh();},
  });
  return <main>
    <PageHero eyebrow="ARCHIVE VAULT" title="文件管理" description="按权限管理海报、照片、视频、策划案和历史资料。"><button className="guild-button primary" onClick={()=>setOpen(!open)}>{open?'取消上传':'上传文件'}</button></PageHero>
    <section className="shell">
      {open&&<form className="inline-create" onSubmit={e=>{e.preventDefault();upload.mutate();}}>
        <label>选择文件<input type="file" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>
        <label>可见范围<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="MEMBERS">全体成员</option><option value="DEPARTMENT">仅所属部门</option>{user?.role==='ADMIN'&&<><option value="PUBLIC">公开</option><option value="ADMINS">仅管理员</option></>}</select></label>
        <label>业务分类<select value={category} onChange={e=>setCategory(e.target.value)}><option value="POSTER">活动海报</option><option value="PHOTO">活动照片</option><option value="VIDEO">活动视频</option><option value="PLAN">策划文档</option><option value="HISTORY">历史资料</option><option value="OTHER">其他资料</option></select></label>
        <label>所属部门<select value={departmentId} disabled={user?.role!=='ADMIN'} onChange={e=>setDepartmentId(e.target.value)}><option value="dept-cos">COS部</option><option value="dept-tech">技术部</option><option value="dept-music">轻音部</option><option value="dept-original">原创部</option><option value="dept-dance">舞装部</option><option value="dept-publicity">外宣部</option></select></label>
        {upload.error&&<p className="form-error">{upload.error.message}</p>}
        <button className="guild-button primary" disabled={!file||upload.isPending}>保存文件</button>
      </form>}
      {query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:<div className="file-grid">{query.data?.items.map(item=><article className={item.deleted_at?'trashed':''} key={item.id}><FileArchive/><div><StatusBadge status={item.visibility}/><h2>{item.name}</h2><p>{item.category} · {item.mime_type} · {(item.size/1024).toFixed(1)} KB</p></div><div className="row-actions">{!item.deleted_at&&<button onClick={()=>{const name=prompt('输入新的文件名',item.name);if(name&&name!==item.name)rename.mutate({id:item.id,name});}}>重命名</button>}{item.deleted_at?<button onClick={()=>action.mutate({id:item.id,verb:'restore'})}><ArchiveRestore/>恢复</button>:<button className="danger" onClick={()=>action.mutate({id:item.id,verb:'recycle'})}><Trash2/>回收</button>}</div></article>)}</div>}
    </section>
  </main>;
}

export function TasksAdminPage(){
  const {user}=useAuth(); const refresh=useInvalidate('admin-tasks','admin-analytics'); const [open,setOpen]=useState(false); const [form,setForm]=useState({departmentId:user?.departmentId??'dept-cos',assigneeId:'',title:'',description:'',dueAt:'2026-08-30T12:00:00.000Z'});
  const query=useQuery({queryKey:['admin-tasks'],queryFn:()=>api<PageData<Task>>('/api/admin/tasks?page=1&pageSize=100')});
  const members=useQuery({queryKey:['admin-members','task'],queryFn:()=>api<PageData<Member>>('/api/admin/members?page=1&pageSize=100')});
  const confirm=useMutation({mutationFn:(id:string)=>api(`/api/admin/tasks/${id}/confirm`,json('POST')),onSuccess:refresh});
  const create=useMutation({mutationFn:()=>api('/api/admin/tasks',json('POST',form)),onSuccess:()=>{setOpen(false);setForm({...form,title:'',description:'',assigneeId:''});refresh();}});
  const candidates=members.data?.items.filter(member=>member.department_id===form.departmentId)??[];
  return <main><PageHero eyebrow="QUEST ASSIGNMENT" title="部门任务" description="负责人指派任务，成员完成后确认贡献且只计入一次。"><button className="guild-button primary" onClick={()=>setOpen(!open)}>{open?'取消指派':'指派新任务'}</button></PageHero><section className="shell">{open&&<form className="inline-create" onSubmit={e=>{e.preventDefault();create.mutate();}}><label>所属部门<select value={form.departmentId} disabled={user?.role!=='ADMIN'} onChange={e=>setForm({...form,departmentId:e.target.value,assigneeId:''})}><option value="dept-cos">COS部</option><option value="dept-tech">技术部</option><option value="dept-music">轻音部</option><option value="dept-original">原创部</option><option value="dept-dance">舞装部</option><option value="dept-publicity">外宣部</option></select></label><label>指派成员<select required value={form.assigneeId} onChange={e=>setForm({...form,assigneeId:e.target.value})}><option value="">请选择成员</option>{candidates.map(member=><option key={member.id} value={member.id}>{member.display_name}</option>)}</select></label><label>任务名称<input required minLength={2} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>任务说明<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{create.error&&<p className="form-error">{create.error.message}</p>}<button className="guild-button primary">发布任务</button></form>}{query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:<div className="task-board">{query.data?.items.map(t=><article className={t.confirmed_at?'complete':''} key={t.id}><ClipboardCheck/><div><small>{t.confirmed_at?'已确认':t.completed_at?'待确认':'执行中'}</small><h2>{t.title}</h2><p>{t.description}</p></div>{t.completed_at&&!t.confirmed_at&&<button onClick={()=>confirm.mutate(t.id)}><Check/>确认贡献</button>}</article>)}</div>}</section></main>;
}

export function ChronicleAdminPage(){
  const refresh=useInvalidate('chronicles'); const [form,setForm]=useState({title:'',content:'',occurredAt:new Date().toISOString(),published:true}); const query=useQuery({queryKey:['chronicles'],queryFn:()=>api<PageData<Chronicle>>('/api/public/chronicles?page=1&pageSize=100')}); const create=useMutation({mutationFn:()=>api('/api/admin/chronicles',json('POST',form)),onSuccess:()=>{setForm({...form,title:'',content:''});refresh();}});
  return <main><PageHero eyebrow="CHRONICLE EDITOR" title="历史管理" description="后台新增的时间线节点会立即显示在公会编年史。"/><section className="shell detail-columns"><form className="inline-create" onSubmit={e=>{e.preventDefault();create.mutate();}}><h2>新增历史节点</h2><label>标题<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>描述<textarea required value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><button className="guild-button primary">发布到编年史</button></form><article className="parchment-panel"><h2>现有节点</h2>{query.data?.items.map(c=><div className="quest-row" key={c.id}><History/><span>{new Date(c.occurred_at).getFullYear()}</span><strong>{c.title}</strong></div>)}</article></section></main>;
}

export function AnalyticsAdminPage(){const query=useQuery({queryKey:['admin-analytics'],queryFn:()=>api<Analytics>('/api/admin/analytics')});return <main><PageHero eyebrow="GUILD INTELLIGENCE" title="数据统计" description="成员增长、活动数量、部门活跃度、贡献排行与年度报告。"/><section className="shell chart-grid">{query.isLoading?<LoadingPanel/>:<><article className="chart-panel"><h2>成员增长</h2><ResponsiveContainer width="100%" height={320}><BarChart data={query.data?.memberGrowth??[]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Bar dataKey="count" fill="#4b9cd3"/></BarChart></ResponsiveContainer></article><article className="chart-panel"><h2>部门活跃度</h2><ResponsiveContainer width="100%" height={320}><BarChart data={query.data?.departmentActivity??[]} layout="vertical"><XAxis type="number"/><YAxis type="category" dataKey="departmentName" width={80}/><Tooltip/><Bar dataKey="score" fill="#c89b3c"/></BarChart></ResponsiveContainer></article></>}</section><section className="shell report-actions"><button className="guild-button" onClick={()=>window.print()}>打印年度报告</button><button className="guild-button ghost" onClick={()=>{const rows=query.data?.departmentActivity??[];const csv=['部门,活跃度',...rows.map(r=>`${r.departmentName},${r.score}`)].join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='佐佑动漫社年度报告.csv';a.click();URL.revokeObjectURL(url);}}>导出统计 CSV</button></section></main>}

export function SettingsAdminPage(){const [settings,setSettings]=useState<Record<string,string>>({});const query=useQuery({queryKey:['admin-settings'],queryFn:async()=>{const d=await api<{settings:Record<string,string>}>('/api/admin/site-settings');setSettings(d.settings);return d;}});const save=useMutation({mutationFn:()=>api('/api/admin/site-settings',json('PUT',settings))});return <main><PageHero eyebrow="GUILD CONFIGURATION" title="系统设置" description="维护站点名称、欢迎语、公会等级和招新开关。"/><section className="shell narrow">{query.isLoading?<LoadingPanel/>:<form className="parchment-form" onSubmit={e=>{e.preventDefault();save.mutate();}}><label>站点名称<input value={settings.siteName??''} onChange={e=>setSettings({...settings,siteName:e.target.value})}/></label><label>首页欢迎语<input value={settings.welcomeMessage??'欢迎来到冒险者公会'} onChange={e=>setSettings({...settings,welcomeMessage:e.target.value})}/></label><label>公会等级<input value={settings.guildLevel??'12'} onChange={e=>setSettings({...settings,guildLevel:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={settings.recruitmentOpen!=='false'} onChange={e=>setSettings({...settings,recruitmentOpen:String(e.target.checked)})}/>开放招新</label>{save.isSuccess&&<p className="form-success">设置已保存</p>}<button className="guild-button primary"><Settings/>保存设置</button></form>}</section></main>}

export function AuditAdminPage(){const query=useQuery({queryKey:['admin-audit'],queryFn:()=>api<PageData<Audit>>('/api/admin/audit-log?page=1&pageSize=100')});return <main><PageHero eyebrow="AUDIT TRAIL" title="审计日志" description="记录登录、审核、状态迁移和贡献确认等关键管理操作。"/><section className="shell">{query.isLoading?<LoadingPanel/>:query.error?<ErrorPanel error={query.error}/>:<div className="audit-list">{query.data?.items.map(a=><article key={a.id}><CircleGauge/><div><strong>{a.action}</strong><span>{a.entity_type} · {a.entity_id}</span></div><time>{formatDate(a.created_at)}</time></article>)}</div>}</section></main>}

function AdminListPage({title,eyebrow,description,search,onSearch,children}:{title:string;eyebrow:string;description:string;search:string;onSearch:(value:string)=>void;children:React.ReactNode}){return <main><PageHero eyebrow={eyebrow} title={title} description={description}/><section className="shell"><label className="search-box"><Search/><span className="sr-only">搜索</span><input value={search} onChange={e=>onSearch(e.target.value)} placeholder="搜索成员名称或邮箱"/></label>{children}</section></main>}
